# Generated by Django 5.2.4 on 2026-02-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_issues", models.IntegerField(default=0)),
                ("high_issues", models.IntegerField(default=0)),
                ("medium_issues", models.IntegerField(default=0)),
                ("low_issues", models.IntegerField(default=0)),
            ],
        ),
    ]
