# Generated by Django 6.0.2 on 2026-02-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
    ]
