# Generated by Django 6.0.2 on 2026-02-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_scan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="raw_report",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
